
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'
import PageWrapper from '@/components/PageWrapper'
import Nav from '@/components/Nav'
import Presence_Provider from '@/components/Presence_Provider'

export const metadata = {
  title: 'NBeauty',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Presence_Provider>
        <Nav/>
      <PageWrapper>
      {children}
      </PageWrapper>
      
      <Footer/>
        </Presence_Provider>
      </body>
      
    </html>
  )
}
